### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by stellanhaglund** [IonicaBizau/nodeice#13]
hi again! :)

I'm trying to run this app from docker but I get this

/node_modules/phantom-html-to-pdf/lib/conversion.js:83
    if (opt.phantomPath) {
           ^

TypeError: Cannot read property 'phantomPath' of undefined
    at module.exports (/node_modules/phantom-html-to-pdf/lib/conversion.js:83:12)
    at Object.<anonymous> (/lib/index.js:11:45)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/example/index.js:2:15)
    at Module._compile (module.js:397:26)

any ideas?

**Comment by bjrmatos** [comment]
sorry for the issue! it has been fixed in `phantom-html-to-pdf` master, just wait for a new release

**Comment by IonicaBizau** [comment]
@stellanhaglund Thanks for reporting! :+1: 
@bjrmatos Thanks for fixing! :sparkles:
