### ISSUE TITLE
Error with unitPrice.main as number

### ISSUE THREAD

**Issue by kill4food** [IonicaBizau/nodeice#20]
Hi, when i tried to send unitPrice.main = 2 (number) then i got the following error:
`TypeError: Cannot read property 'toFixed' of undefined
                                                                  at /user_code/node_modules/nodeice/lib/index.js:133:78
                                                                  at iterateObject (/user_code/node_modules/nodeice/node_modules/iterate-object/lib/index.js:18:17)
                                                                  at /user_code/node_modules/nodeice/lib/index.js:120:17
                                                                  at /user_code/node_modules/nodeice/lib/index.js:73:21
                                                                  at /user_code/node_modules/nodeice/node_modules/same-time/lib/index.js:71:22
                                                                  at tryToString (fs.js:455:3)
                                                                  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)`

I fixed it by wrapping the number in a variable and invoking on it var.toString()
But it's weird, because using a number in that field as a price is more intuitive than using a string.

**Comment by IonicaBizau** [comment]
If it's a number, `toFixed` should work. I cannot reproduce this (anymore).
